[tool.poetry]
name = "scleaner"
version = "2.0.0"
description = "Removes all shortcuts from the user's Desktop folder, with optional exceptions."
authors = ["Rain <Rainyan@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [
	{ include = "cleaner.py", from = "src" },
	{ include = "thirdparty", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.scripts]
scleaner = "cleaner:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
extend-exclude = ["src/thirdparty"]
