name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Pls
        working-directory: src
        shell: cmd
        run: dir

      - name: Get desktop directory path
        working-directory: src
        shell: python
        run: |
          import os
          import cleaner

          desktop = cleaner.get_known_path("Desktop")
          assert os.path.isdir(desktop)

          env = os.getenv("GITHUB_ENV")
          assert env is not None

          print(f"DESKTOP={desktop}")
          #with open(env, "w") as f:
          #  f.write(f"DESKTOP={desktop}")

      - name: Check dir
        shell: cmd
        run: |
          ECHO GITHUB_ENV: %GITHUB_ENV%
