name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: poetry

      - name: Install the app
        run: |
          pipx install poetry --python $(which python)
          pipx install .

      - name: Test
        shell: cmd
        run: |
          FOR /F "tokens=* USEBACKQ" %%F IN (`scleaner --print-my-desktop-dir`) DO (
          SET DESKTOP=%%F
          )
          CD /D %DESKTOP%

          SET TEST_FILE=foo.lnk
          FOR %%f in ("%TEST_FILE%") DO SET TEST_FILE_NO_EXT=%%~nf

          REM File already exists
          IF EXIST ".\%TEST_FILE%" (EXIT 1)

          ECHO NUL > %TEST_FILE%
          REM File doesn't exist after creation
          IF NOT EXIST ".\%TEST_FILE%" (EXIT 2)

          scleaner
          REM Dry-run fails
          IF NOT EXIST ".\%TEST_FILE%" (EXIT 3)

          scleaner -e %TEST_FILE_NO_EXT% -f
          REM Filename exception fails
          IF NOT EXIST ".\%TEST_FILE%" (EXIT 4)

          scleaner -f -e %TEST_FILE_NO_EXT%
          REM Filename exception fails
          IF NOT EXIST ".\%TEST_FILE%" (EXIT 5)

          scleaner -f -d "PublicDesktop"
          REM Wrong desktop folder is cleaned
          IF NOT EXIST ".\%TEST_FILE%" (EXIT 6)

          scleaner --print-my-desktop-dir
          REM Print-my-desktop doesn't exit correctly
          IF NOT EXIST ".\%TEST_FILE%" (EXIT 7)

          scleaner -f
          REM The file is not removed even though it should
          IF EXIST ".\%TEST_FILE%" (EXIT 8)
