name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install the app
        shell: cmd
        run: |
          pip install -U pipx
          pipx install .

      - name: Get desktop directory path
        working-directory: src
        shell: bash
        run: |
          DESKTOP = $(scleaner --print-my-desktop-dir)
          echo "{DESKTOP}={$DESKTOP}" >> "$GITHUB_ENV"

      - name: Check dir
        shell: cmd
        run: |
          ECHO GITHUB_ENV: %GITHUB_ENV%
