name: Test

on: push

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v6
        with:
          python-version-file: 'pyproject.toml'

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: "0.11.23"

      - name: Install the app
        run: uv tool install .

      - name: Test
        shell: cmd
        run: |
          :: Call EXIT for real on the CI script run so we can fail properly
          sed "s/ECHO EXIT/EXIT/" .\test.bat > .\test.bat.fixup
          MOVE /Y .\test.bat.fixup .\test.bat
          CMD /C .\test.bat
